/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/

const express = require('express');
const app = express();

// Disable the X-Powered-By header globally
app.disable('x-powered-by');

// Middleware for setting custom headers
app.use(function (req, res, next) {
  res.set({
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, content-type, Accept',
  });
  next();
});

// Serve static files from the public folder
app.use(express.static('public'));

// Require the main app routes from myApp.js
const mainApp = require('./myApp.js');
app.use('/', mainApp);

// Handle app-info endpoint to show middleware stack and headers
app.get('/app-info', function (req, res) {
  if (mainApp._router) {
    var appMainRouteStack = mainApp._router.stack
      .filter((s) => s.path === '')
      .map((l) => l.name)
      .filter((n) => !(n === 'query' || n === 'expressInit' || n === 'serveStatic'));

    var hs = Object.keys(res.getHeaders()).filter((h) => !h.match(/^access-control-\w+/));
    var hObj = {};
    hs.forEach((h) => {
      hObj[h] = res.getHeaders()[h];
    });
    delete res.get('strict-transport-security');
    res.json({ headers: hObj, appStack: appMainRouteStack });
  } else {
    res.status(500).send('Main app routes are not initialized correctly.');
  }
});

// Handle package.json file access
app.get('/package.json', function (req, res, next) {
  fs.readFile(__dirname + '/package.json', function (err, data) {
    if (err) return next(err);
    res.type('txt').send(data.toString());
  });
});

// Error handling for 404 requests
app.use(function (req, res, next) {
  res.status(404).type('txt').send('Not Found');
});

// Use the port defined in the environment (Render automatically sets this)
const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
  console.log(`✅ Server is listening on port ${PORT}`);
});

module.exports = app;

/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/
